# Generated by Django 4.2.5 on 2024-04-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_hotel_hotelreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='discription',
            new_name='description',
        ),
    ]
