# Generated by Django 4.2.5 on 2024-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_discription_hotel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelReviewFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_fake', models.BooleanField(default=False)),
            ],
        ),
    ]
