# Generated by Django 5.0.3 on 2024-05-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_hotelreviewfine"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelreviewfine",
            name="hotel_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
